// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ESPGrind

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main( lv_event_t * e);
lv_obj_t *ui_Main;
lv_obj_t *ui_Header;
void ui_event_Settings( lv_event_t * e);
lv_obj_t *ui_Settings;
lv_obj_t *ui_SettingsLabel;
void ui_event_GrindIII( lv_event_t * e);
lv_obj_t *ui_GrindIII;
lv_obj_t *ui_GrindIIILabel;
lv_obj_t *ui_Edit;
lv_obj_t *ui_LockLabel;
lv_obj_t *ui_Controls;
void ui_event_GrindI( lv_event_t * e);
lv_obj_t *ui_GrindI;
lv_obj_t *ui_GrindILabel;
lv_obj_t *ui_ContainerM;
void ui_event_GrindM( lv_event_t * e);
lv_obj_t *ui_GrindM;
lv_obj_t *ui_GrindMLabel;
void ui_event_GrindII( lv_event_t * e);
lv_obj_t *ui_GrindII;
lv_obj_t *ui_GrindIILabel;
lv_obj_t *ui_Footer;
void ui_event_Minus( lv_event_t * e);
lv_obj_t *ui_Minus;
lv_obj_t *ui_MinusLabel;
lv_obj_t *ui_TimerBox;
lv_obj_t *ui_Timer;
lv_obj_t *ui_TimerSecondsLabel;
void ui_event_Plus( lv_event_t * e);
lv_obj_t *ui_Plus;
lv_obj_t *ui_PlusLabel;
// CUSTOM VARIABLES


// SCREEN: ui_SettingsMain
void ui_SettingsMain_screen_init(void);
void ui_event_SettingsMain( lv_event_t * e);
lv_obj_t *ui_SettingsMain;
lv_obj_t *ui_HeaderSettings;
void ui_event_SettingsExit( lv_event_t * e);
lv_obj_t *ui_SettingsExit;
lv_obj_t *ui_SettingsExitLabel;
void ui_event_SettingsHeadlineLabel( lv_event_t * e);
lv_obj_t *ui_SettingsHeadlineLabel;
lv_obj_t *ui_SettingsContents;
lv_obj_t *ui_BrightnessPanel;
lv_obj_t *ui_Label1;
void ui_event_BrightnessSlider( lv_event_t * e);
lv_obj_t *ui_BrightnessSlider;
lv_obj_t *ui_EditEnablePanel;
lv_obj_t *ui_Label2;
void ui_event_EditEnable( lv_event_t * e);
lv_obj_t *ui_EditEnable;
lv_obj_t *ui_ScreensaverSettingsPanel;
lv_obj_t *ui_Label3;
lv_obj_t *ui_ScreensaverTimeout;
lv_obj_t *ui_VersionPanel;
lv_obj_t *ui_Label4;
lv_obj_t *ui_VersionLabel;
lv_obj_t *ui_CounterContainer;
lv_obj_t *ui_CounterPanel1;
lv_obj_t *ui_CounterLabel1;
lv_obj_t *ui_Counter1;
lv_obj_t *ui_CounterPanel2;
lv_obj_t *ui_CounterLabel2;
lv_obj_t *ui_Counter2;
lv_obj_t *ui_CounterPanel3;
lv_obj_t *ui_CounterLabel3;
lv_obj_t *ui_Counter3;
lv_obj_t *ui_CounterPanel4;
lv_obj_t *ui_CounterLabel4;
lv_obj_t *ui_Counter4;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenSaver
void ui_ScreenSaver_screen_init(void);
lv_obj_t *ui_ScreenSaver;
lv_obj_t *ui_standbyLabel;
lv_obj_t *ui_standbyInfoLabel;
// CUSTOM VARIABLES

// EVENTS
void ui_event____initial_actions0( lv_event_t * e);
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Main( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onMainScreenLoaded( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_SettingsMain, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0, &ui_SettingsMain_screen_init);
}
}

void ui_event_Settings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SettingsMain, LV_SCR_LOAD_ANIM_MOVE_TOP, 250, 0, &ui_SettingsMain_screen_init);
}
}

void ui_event_GrindIII( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onGrindClicked( e );
}
if ( event_code == LV_EVENT_FOCUSED) {
      onGrindFocussed( e );
}
}

void ui_event_GrindI( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onGrindClicked( e );
}
if ( event_code == LV_EVENT_FOCUSED) {
      onGrindFocussed( e );
}
}

void ui_event_GrindM( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_FOCUSED) {
      onGrindFocussed( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      onGrindClicked( e );
}
if ( event_code == LV_EVENT_PRESSED) {
      onManualGrindPush( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      onManualGrindPush( e );
}
}

void ui_event_GrindII( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onGrindClicked( e );
}
if ( event_code == LV_EVENT_FOCUSED) {
      onGrindFocussed( e );
}
}

void ui_event_Minus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SHORT_CLICKED) {
      onDecreaseTime1( e );
}
}

void ui_event_Plus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SHORT_CLICKED) {
      onIncreaseTime1( e );
}
}

void ui_event_SettingsMain( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onSettingsScreenLoaded( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0, &ui_Main_screen_init);
}
}

void ui_event_SettingsExit( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 250, 0, &ui_Main_screen_init);
}
}

void ui_event_SettingsHeadlineLabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_SettingsMain, LV_SCR_LOAD_ANIM_MOVE_TOP, 250, 0, &ui_SettingsMain_screen_init);
}
}

void ui_event_BrightnessSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      onBrightnessChanged( e );
}
}

void ui_event_EditEnable( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      editEnableChanged( e );
}
}

void ui_event____initial_actions0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      ui_InitialActions( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Main_screen_init();
ui_SettingsMain_screen_init();
ui_ScreenSaver_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

lv_disp_load_scr(ui____initial_actions0);
lv_disp_load_scr( ui_Main);
}
