// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ESPGrind

#ifndef _ESPGRIND_UI_H
#define _ESPGRIND_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main( lv_event_t * e);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_Header;
void ui_event_Settings( lv_event_t * e);
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_SettingsLabel;
void ui_event_GrindIII( lv_event_t * e);
extern lv_obj_t *ui_GrindIII;
extern lv_obj_t *ui_GrindIIILabel;
extern lv_obj_t *ui_Edit;
extern lv_obj_t *ui_LockLabel;
extern lv_obj_t *ui_Controls;
void ui_event_GrindI( lv_event_t * e);
extern lv_obj_t *ui_GrindI;
extern lv_obj_t *ui_GrindILabel;
extern lv_obj_t *ui_ContainerM;
void ui_event_GrindM( lv_event_t * e);
extern lv_obj_t *ui_GrindM;
extern lv_obj_t *ui_GrindMLabel;
void ui_event_GrindII( lv_event_t * e);
extern lv_obj_t *ui_GrindII;
extern lv_obj_t *ui_GrindIILabel;
extern lv_obj_t *ui_Footer;
void ui_event_Minus( lv_event_t * e);
extern lv_obj_t *ui_Minus;
extern lv_obj_t *ui_MinusLabel;
extern lv_obj_t *ui_TimerBox;
extern lv_obj_t *ui_Timer;
extern lv_obj_t *ui_TimerSecondsLabel;
void ui_event_Plus( lv_event_t * e);
extern lv_obj_t *ui_Plus;
extern lv_obj_t *ui_PlusLabel;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsMain
void ui_SettingsMain_screen_init(void);
void ui_event_SettingsMain( lv_event_t * e);
extern lv_obj_t *ui_SettingsMain;
extern lv_obj_t *ui_HeaderSettings;
void ui_event_SettingsExit( lv_event_t * e);
extern lv_obj_t *ui_SettingsExit;
extern lv_obj_t *ui_SettingsExitLabel;
void ui_event_SettingsHeadlineLabel( lv_event_t * e);
extern lv_obj_t *ui_SettingsHeadlineLabel;
extern lv_obj_t *ui_SettingsContents;
extern lv_obj_t *ui_BrightnessPanel;
extern lv_obj_t *ui_Label1;
void ui_event_BrightnessSlider( lv_event_t * e);
extern lv_obj_t *ui_BrightnessSlider;
extern lv_obj_t *ui_EditEnablePanel;
extern lv_obj_t *ui_Label2;
void ui_event_EditEnable( lv_event_t * e);
extern lv_obj_t *ui_EditEnable;
extern lv_obj_t *ui_ScreensaverSettingsPanel;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_ScreensaverTimeout;
extern lv_obj_t *ui_VersionPanel;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_VersionLabel;
extern lv_obj_t *ui_CounterContainer;
extern lv_obj_t *ui_CounterPanel1;
extern lv_obj_t *ui_CounterLabel1;
extern lv_obj_t *ui_Counter1;
extern lv_obj_t *ui_CounterPanel2;
extern lv_obj_t *ui_CounterLabel2;
extern lv_obj_t *ui_Counter2;
extern lv_obj_t *ui_CounterPanel3;
extern lv_obj_t *ui_CounterLabel3;
extern lv_obj_t *ui_Counter3;
extern lv_obj_t *ui_CounterPanel4;
extern lv_obj_t *ui_CounterLabel4;
extern lv_obj_t *ui_Counter4;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSaver
void ui_ScreenSaver_screen_init(void);
extern lv_obj_t *ui_ScreenSaver;
extern lv_obj_t *ui_standbyLabel;
extern lv_obj_t *ui_standbyInfoLabel;
// CUSTOM VARIABLES

// EVENTS
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_MartianExtraBold38);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
