// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ESPGrind

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif


void ui_InitialActions(lv_event_t * e);
void onMainScreenLoaded(lv_event_t * e);
void onAnyClick(lv_event_t * e);
void onGrindClicked(lv_event_t * e);
void onGrindFocussed(lv_event_t * e);
void onManualGrindPush(lv_event_t * e);
void onDecreaseTime1(lv_event_t * e);
void onIncreaseTime1(lv_event_t * e);
void onSettingsScreenLoaded(lv_event_t * e);
void onBrightnessChanged(lv_event_t * e);
void editEnableChanged(lv_event_t * e);
void retriggerScreensaver(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
