// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ESPGrind

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Focussed[1] = {0x3050A0};
const ui_theme_variable_t _ui_theme_alpha_Focussed[1] = {255};

const ui_theme_variable_t _ui_theme_color_Red[1] = {0xAA0000};
const ui_theme_variable_t _ui_theme_alpha_Red[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

