// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ESPGrind

#include "../ui.h"

void ui_Main_screen_init(void)
{
ui_Main = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Main, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_flex_flow(ui_Main,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Main, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header = lv_obj_create(ui_Main);
lv_obj_remove_style_all(ui_Header);
lv_obj_set_width( ui_Header, lv_pct(100));
lv_obj_set_height( ui_Header, lv_pct(26));
lv_obj_set_x( ui_Header, 0 );
lv_obj_set_y( ui_Header, 48 );
lv_obj_set_align( ui_Header, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Header,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Header, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_Header, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_pad_left(ui_Header, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Header, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Header, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings = lv_button_create(ui_Header);
lv_obj_set_width( ui_Settings, 36);
lv_obj_set_height( ui_Settings, 36);
lv_obj_set_x( ui_Settings, -124 );
lv_obj_set_y( ui_Settings, -2 );
lv_obj_set_align( ui_Settings, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Settings,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Settings, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Settings, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Settings, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Settings, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_Settings, 0, LV_PART_MAIN| LV_STATE_DISABLED);

ui_SettingsLabel = lv_label_create(ui_Settings);
lv_obj_set_width( ui_SettingsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsLabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(ui_SettingsLabel,"S");
lv_obj_set_style_text_font(ui_SettingsLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindIII = lv_arc_create(ui_Header);
lv_obj_set_width( ui_GrindIII, 60);
lv_obj_set_height( ui_GrindIII, 60);
lv_obj_set_x( ui_GrindIII, -19 );
lv_obj_set_y( ui_GrindIII, 4 );
lv_obj_set_align( ui_GrindIII, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_GrindIII,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_GrindIII, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_GrindIII, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_remove_flag( ui_GrindIII, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_GrindIII, LV_SCROLLBAR_MODE_OFF);
lv_arc_set_value(ui_GrindIII, 100);
lv_arc_set_bg_angles(ui_GrindIII,0,360);
lv_arc_set_mode(ui_GrindIII, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_GrindIII,270);
lv_obj_set_style_arc_color(ui_GrindIII, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindIII, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindIII, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_GrindIII, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_GrindIII, 30, LV_PART_MAIN| LV_STATE_FOCUSED);
ui_object_set_themeable_style_property(ui_GrindIII, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Focussed);
ui_object_set_themeable_style_property(ui_GrindIII, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Focussed);

lv_obj_set_style_arc_color(ui_GrindIII, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindIII, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindIII, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_GrindIII, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_GrindIII, lv_color_hex(0x3C50BE), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_arc_opa(ui_GrindIII, 255, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_GrindIII, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrindIII, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_GrindIII, true, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_GrindIIILabel = lv_label_create(ui_GrindIII);
lv_obj_set_width( ui_GrindIIILabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrindIIILabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_GrindIIILabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_GrindIIILabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_GrindIIILabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(ui_GrindIIILabel,"III");
lv_obj_remove_flag( ui_GrindIIILabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_GrindIIILabel, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_GrindIIILabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_text_opa(ui_GrindIIILabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_Edit = lv_button_create(ui_Header);
lv_obj_set_width( ui_Edit, 38);
lv_obj_set_height( ui_Edit, 38);
lv_obj_set_x( ui_Edit, -124 );
lv_obj_set_y( ui_Edit, -2 );
lv_obj_set_align( ui_Edit, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Edit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_Edit, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_Edit, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Edit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Edit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Edit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Edit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Edit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Edit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Edit, lv_color_hex(0xAA0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Edit, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LockLabel = lv_label_create(ui_Edit);
lv_obj_set_width( ui_LockLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LockLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LockLabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_LockLabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_LockLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(ui_LockLabel,"E");
lv_obj_add_state( ui_LockLabel, LV_STATE_CHECKED | LV_STATE_PRESSED | LV_STATE_FOCUSED );     /// States
lv_obj_set_style_text_font(ui_LockLabel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Controls = lv_obj_create(ui_Main);
lv_obj_remove_style_all(ui_Controls);
lv_obj_set_width( ui_Controls, lv_pct(100));
lv_obj_set_height( ui_Controls, lv_pct(44));
lv_obj_set_x( ui_Controls, 1 );
lv_obj_set_y( ui_Controls, 16 );
lv_obj_set_align( ui_Controls, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Controls,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Controls, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Controls, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_remove_flag( ui_Controls, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Controls, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Controls, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Controls, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Controls, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Controls, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Controls, 25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindI = lv_arc_create(ui_Controls);
lv_obj_set_width( ui_GrindI, 80);
lv_obj_set_height( ui_GrindI, 80);
lv_obj_set_x( ui_GrindI, -19 );
lv_obj_set_y( ui_GrindI, 4 );
lv_obj_set_align( ui_GrindI, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_GrindI,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_GrindI, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_GrindI, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_remove_flag( ui_GrindI, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_GrindI, LV_SCROLLBAR_MODE_OFF);
lv_arc_set_value(ui_GrindI, 100);
lv_arc_set_bg_angles(ui_GrindI,0,360);
lv_arc_set_mode(ui_GrindI, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_GrindI,270);
lv_obj_set_style_arc_color(ui_GrindI, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindI, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindI, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_GrindI, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_GrindI, 50, LV_PART_MAIN| LV_STATE_FOCUSED);
ui_object_set_themeable_style_property(ui_GrindI, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Focussed);
ui_object_set_themeable_style_property(ui_GrindI, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Focussed);

lv_obj_set_style_arc_color(ui_GrindI, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindI, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindI, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_GrindI, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_GrindI, lv_color_hex(0x3C50BE), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_arc_opa(ui_GrindI, 255, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_GrindI, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrindI, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_GrindI, true, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_GrindILabel = lv_label_create(ui_GrindI);
lv_obj_set_width( ui_GrindILabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrindILabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_GrindILabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_GrindILabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_GrindILabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(ui_GrindILabel,"I");
lv_obj_remove_flag( ui_GrindILabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_GrindILabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_GrindILabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_text_opa(ui_GrindILabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_ContainerM = lv_obj_create(ui_Controls);
lv_obj_remove_style_all(ui_ContainerM);
lv_obj_set_width( ui_ContainerM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ContainerM, LV_SIZE_CONTENT);   /// 2
lv_obj_set_align( ui_ContainerM, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ContainerM,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContainerM, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_ContainerM, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_ContainerM, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ContainerM, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ContainerM, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ContainerM, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindM = lv_arc_create(ui_ContainerM);
lv_obj_set_width( ui_GrindM, 80);
lv_obj_set_height( ui_GrindM, 80);
lv_obj_set_x( ui_GrindM, -19 );
lv_obj_set_y( ui_GrindM, 4 );
lv_obj_set_align( ui_GrindM, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_GrindM,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_GrindM, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_GrindM, LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_remove_flag( ui_GrindM, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_GrindM, LV_SCROLLBAR_MODE_OFF);
lv_arc_set_value(ui_GrindM, 100);
lv_arc_set_bg_angles(ui_GrindM,0,360);
lv_arc_set_mode(ui_GrindM, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_GrindM,270);
lv_obj_set_style_arc_color(ui_GrindM, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindM, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_GrindM, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_GrindM, 50, LV_PART_MAIN| LV_STATE_CHECKED);
ui_object_set_themeable_style_property(ui_GrindM, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_GrindM, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_radius(ui_GrindM, 50, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_GrindM, lv_color_hex(0x008020), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_GrindM, 250, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_radius(ui_GrindM, 50, LV_PART_MAIN| LV_STATE_FOCUSED);
ui_object_set_themeable_style_property(ui_GrindM, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Focussed);
ui_object_set_themeable_style_property(ui_GrindM, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Focussed);

lv_obj_set_style_arc_color(ui_GrindM, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindM, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindM, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_GrindM, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_GrindM, lv_color_hex(0x3C50BE), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_arc_opa(ui_GrindM, 255, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_GrindM, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrindM, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_GrindM, true, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_GrindMLabel = lv_label_create(ui_GrindM);
lv_obj_set_width( ui_GrindMLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrindMLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_GrindMLabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_GrindMLabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_GrindMLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(ui_GrindMLabel,"M");
lv_obj_add_flag( ui_GrindMLabel, LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_remove_flag( ui_GrindMLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_GrindMLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_GrindMLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_text_opa(ui_GrindMLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_GrindII = lv_arc_create(ui_Controls);
lv_obj_set_width( ui_GrindII, 80);
lv_obj_set_height( ui_GrindII, 80);
lv_obj_set_x( ui_GrindII, -19 );
lv_obj_set_y( ui_GrindII, 4 );
lv_obj_set_align( ui_GrindII, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_GrindII,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_GrindII, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_GrindII, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_remove_flag( ui_GrindII, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_GrindII, LV_SCROLLBAR_MODE_OFF);
lv_arc_set_value(ui_GrindII, 100);
lv_arc_set_bg_angles(ui_GrindII,0,360);
lv_arc_set_mode(ui_GrindII, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_GrindII,270);
lv_obj_set_style_arc_color(ui_GrindII, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindII, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindII, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_GrindII, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_GrindII, 50, LV_PART_MAIN| LV_STATE_FOCUSED);
ui_object_set_themeable_style_property(ui_GrindII, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Focussed);
ui_object_set_themeable_style_property(ui_GrindII, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Focussed);

lv_obj_set_style_arc_color(ui_GrindII, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindII, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindII, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_GrindII, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_GrindII, lv_color_hex(0x3C50BE), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_arc_opa(ui_GrindII, 255, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_GrindII, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrindII, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_GrindII, true, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_GrindIILabel = lv_label_create(ui_GrindII);
lv_obj_set_width( ui_GrindIILabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrindIILabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_GrindIILabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_GrindIILabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_GrindIILabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(ui_GrindIILabel,"II");
lv_obj_remove_flag( ui_GrindIILabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_GrindIILabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_GrindIILabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_text_opa(ui_GrindIILabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_Footer = lv_obj_create(ui_Main);
lv_obj_remove_style_all(ui_Footer);
lv_obj_set_width( ui_Footer, lv_pct(100));
lv_obj_set_height( ui_Footer, lv_pct(20));
lv_obj_set_x( ui_Footer, 1 );
lv_obj_set_y( ui_Footer, 16 );
lv_obj_set_align( ui_Footer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Footer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Footer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_Footer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_Footer, LV_SCROLLBAR_MODE_OFF);

ui_Minus = lv_button_create(ui_Footer);
lv_obj_set_width( ui_Minus, 40);
lv_obj_set_height( ui_Minus, 40);
lv_obj_set_align( ui_Minus, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Minus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Minus, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Minus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Minus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Minus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Minus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Minus, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MinusLabel = lv_label_create(ui_Minus);
lv_obj_set_width( ui_MinusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MinusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MinusLabel,"--");
lv_obj_set_style_text_color(ui_MinusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MinusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_MinusLabel, -7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_MinusLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MinusLabel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MinusLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MinusLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MinusLabel, -4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MinusLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimerBox = lv_obj_create(ui_Footer);
lv_obj_remove_style_all(ui_TimerBox);
lv_obj_set_width( ui_TimerBox, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimerBox, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimerBox, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TimerBox,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TimerBox, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_TimerBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TimerBox, LV_SCROLLBAR_MODE_OFF);

ui_Timer = lv_spinbox_create(ui_TimerBox);
lv_obj_set_width( ui_Timer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Timer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Timer, 0 );
lv_obj_set_y( ui_Timer, -7 );
lv_obj_set_align( ui_Timer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Timer, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_remove_flag( ui_Timer, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_spinbox_set_digit_format( ui_Timer, 4, 2);
lv_spinbox_set_range( ui_Timer, 0,9999 );
lv_spinbox_set_cursor_pos(ui_Timer, 1 - 1);
lv_spinbox_set_value( ui_Timer, 197 );
lv_obj_set_style_bg_color(ui_Timer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Timer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Timer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Timer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Timer, &ui_font_MartianExtraBold38, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Timer, lv_color_hex(0xAA0000), LV_PART_CURSOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Timer, 0, LV_PART_CURSOR| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Timer, LV_PART_CURSOR| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Timer, LV_PART_CURSOR| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);

ui_TimerSecondsLabel = lv_label_create(ui_TimerBox);
lv_obj_set_height( ui_TimerSecondsLabel, 38);
lv_obj_set_width( ui_TimerSecondsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_TimerSecondsLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_TimerSecondsLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_TimerSecondsLabel,"s");
lv_obj_remove_flag( ui_TimerSecondsLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TimerSecondsLabel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_letter_space(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimerSecondsLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimerSecondsLabel, &ui_font_MartianExtraBold38, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TimerSecondsLabel, -4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TimerSecondsLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Plus = lv_button_create(ui_Footer);
lv_obj_set_width( ui_Plus, 40);
lv_obj_set_height( ui_Plus, 40);
lv_obj_set_align( ui_Plus, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Plus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Plus, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Plus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Plus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Plus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Plus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Plus, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PlusLabel = lv_label_create(ui_Plus);
lv_obj_set_width( ui_PlusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PlusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PlusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PlusLabel,"+");
lv_obj_set_style_text_color(ui_PlusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PlusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PlusLabel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SettingsLabel, ui_event_SettingsLabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GrindIII, ui_event_GrindIII, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GrindI, ui_event_GrindI, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GrindM, ui_event_GrindM, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GrindII, ui_event_GrindII, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Minus, ui_event_Minus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Plus, ui_event_Plus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);

}
